DELETE http://localhost:3001/api/persons/3 HTTP/1.1

###

GET http://localhost:3001/api/persons/649f3d41c84b1f8c1a3bf6eb HTTP/1.1

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Thom Sample",
    "number": "99-88-77"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "",
    "number": "99-88-77"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Thom Sample",
    "number": ""
}

###

POST https://phonebook-backend-puxb.onrender.com/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Thom Sample Ren",
    "number": "99-88-77"
}